[tool.poetry]
name = "strawberry-django-jwt"
version = "0.1.1-a3"
description = "Strawberry-graphql port of the graphene-django-jwt package"
license = "MIT"
authors = ["KundaPanda <vojdoh@gmail.com>"]
maintainers = []
readme = "README.md"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Environment :: Web Environment',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Framework :: Django',
    'Framework :: Django :: 3.0',
    'Framework :: Django :: 3.1',
    'Framework :: Django :: 3.2',
]
exclude = ["tests/"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.0"
PyJWT = "^2.1.0"
strawberry-graphql = "^0.67.1"
strawberry-graphql-django = "^0.2.2"
django-admin-display = "^1.3.0"

[tool.poetry.dev-dependencies]
cryptography = "^3.4.7"
coverage = "^5.5"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-django = "^4.0.0"
nox = "^2021.6.12"
types-cryptography = "^3.3.3"
django-stubs = "^1.8.0"
django-mock-queries = "^2.1.6"
types-mock = "^0.1.3"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
DJANGO_SETTINGS_MODULE = "tests.settings"
python_files = "tests.py test_*.py *_tests.py"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
